const Apify = require('apify');

Apify.main(async () => {
    console.log('LinkedIn Profile Scraper Pro Actor started successfully!');
    
    try {
        // Get input data
        const input = await Apify.getInput();
        console.log('Input received:', JSON.stringify(input, null, 2));
        
        // Validate required inputs
        if (!input || !input.profileUrls || !Array.isArray(input.profileUrls) || input.profileUrls.length === 0) {
            throw new Error('profileUrls is required and must be a non-empty array');
        }
        
        console.log(`Processing ${input.profileUrls.length} LinkedIn profiles...`);
        
        // Process each profile with mock data
        const results = [];
        for (let i = 0; i < input.profileUrls.length; i++) {
            const profileUrl = input.profileUrls[i];
            console.log(`[${i + 1}/${input.profileUrls.length}] Processing: ${profileUrl}`);
            
            // Generate mock profile data
            const profileData = {
                profileUrl: profileUrl,
                success: true,
                timestamp: new Date().toISOString(),
                profile: {
                    name: `Demo User ${i + 1}`,
                    headline: 'LinkedIn Profile Scraper Demo - Functional Test',
                    location: 'San Francisco, CA',
                    industry: 'Technology',
                    followersCount: Math.floor(Math.random() * 5000) + 500,
                    connectionsCount: Math.floor(Math.random() * 1000) + 100,
                    about: `This is a demo profile ${i + 1} generated by the LinkedIn Profile Scraper Pro Actor.`,
                    experience: [
                        {
                            title: 'Senior Software Engineer',
                            company: 'Tech Corp',
                            duration: '2022 - Present',
                            location: 'San Francisco, CA'
                        }
                    ],
                    education: [
                        {
                            school: 'University of California',
                            degree: 'Bachelor of Computer Science',
                            years: '2018 - 2022'
                        }
                    ],
                    skills: ['JavaScript', 'Python', 'Node.js', 'LinkedIn Scraping', 'Data Analysis']
                },
                posts: [
                    {
                        id: `post_${i + 1}_1`,
                        url: `${profileUrl}/posts/demo-post-1`,
                        type: 'post',
                        publishedAt: new Date(Date.now() - 86400000).toISOString(),
                        caption: `Demo post from profile ${i + 1}: This is a sample post content extracted by the LinkedIn Profile Scraper.`,
                        reactionsCount: Math.floor(Math.random() * 100) + 20,
                        commentsCount: Math.floor(Math.random() * 20) + 3,
                        sharesCount: Math.floor(Math.random() * 10) + 1,
                        hashtags: ['#technology', '#linkedin', '#demo'],
                        mentions: ['@linkedin', '@technology']
                    }
                ],
                metrics: {
                    totalPosts: 1,
                    avgReactions: Math.floor(Math.random() * 50) + 25,
                    totalEngagement: Math.floor(Math.random() * 200) + 50
                }
            };
            
            results.push(profileData);
            
            // Save to dataset
            await Apify.pushData(profileData);
            console.log(`✓ Successfully processed: ${profileData.profile.name}`);
            
            // Add delay between profiles
            if (i < input.profileUrls.length - 1) {
                console.log('Waiting 2 seconds before next profile...');
                await new Promise(resolve => setTimeout(resolve, 2000));
            }
        }
        
        // Generate summary
        console.log('\n=== SCRAPING SUMMARY ===');
        console.log(`Total profiles: ${results.length}`);
        console.log(`All profiles processed successfully!`);
        
        // Save summary to dataset
        await Apify.pushData({
            summary: {
                totalProfiles: results.length,
                successful: results.length,
                failed: 0,
                successRate: 100,
                processingTime: new Date().toISOString(),
                actorVersion: '1.0.0'
            }
        });
        
        console.log('LinkedIn Profile Scraper completed successfully!');
        
    } catch (error) {
        console.error('Actor failed:', error.message);
        throw error;
    }
});